### ISSUE TITLE
DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO

### ISSUE THREAD

**Issue by ssg8288** [ssg8288/DEV_SCRIPT_WOC_2020#6]
@DWOC

- [ ] REQUIRES DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO

**Comment by Rishitasharma2001** [comment]
I would like to work on this issue. Please assign it to me. Also, please elaborate on what are your requirements.

**Comment by ssg8288** [comment]
> 
> 
> I would like to work on this issue. Please assign it to me. Also, please elaborate on what are your requirements.

Thanks for showing an interest in this issue @Rishitasharma2001. I have assigned you this issue. 
The requirements are stated below:

- [ ] prepare full documentation of GPS tracking of the vehicle can be done.
- [ ] provide block diagrams and circuit diagrams for better explanation circuits can be made using fritzing software.
- [ ] Also list the components used and what header files are required to be included while writing its code.

Make sure to star and fork it before starting. Feel free to ping me if you feel stuck somewhere.

**Comment by Zircoz** [comment]
Same for this one, it's just level 2 issue. @ssg8288

**Comment by Pranjal-2001** [comment]
I am interested. Can I start working on this issue?

**Comment by ssg8288** [comment]
> 
> 
> I am interested. Can I start working on this issue?

Yes definitely you are in
